version: '3'
services:
  nginx:
    image: gershom/nginx
    stdin_open: true
    tty: true
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - electricityweb
  electricityapi:
    build: ./nodejs-backend
    ports:
      - 8000:8000
  electricityweb:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db/electricity
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - electricity:/data/db
volumes:
  electricity:
